// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pfbtdtwixuunfnidpnqr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBmYnRkdHdpeHV1bmZuaWRwbnFyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM1NTI0NDMsImV4cCI6MjA2OTEyODQ0M30.lNYareir7dwjoIiksuTfUsnJ0uSYV1HY5uxj4x0G4vo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});